////////////////////////////////////////////////////////////////////////
//
// EDIFactSettings.cs
//
// This file was generated by MapForce 2021r3.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

namespace Altova.TextParser.EDI
{
	/// <summary>
	/// Encapsulates EDIFact specific settings
	/// </summary>
	public class EDIFactSettings : EDISettings
	{
		#region Implementation Detail:
		long mSyntaxVersionNumber = 2;
		char mSyntaxLevel = 'A';
		bool mWriteUNA = true;
		#endregion
		#region Public Interface:
		
		public EDIFactSettings () 
		{
			mEDIStandard = EDIStandard.EDIFact;
			mControllingAgency = "UNO";
		}
		
		/// <summary>
		/// Get/sets the syntax version number.
		/// </summary>
		public long SyntaxVersionNumber
		{
			get
			{
				return mSyntaxVersionNumber;
			}
			set
			{
				mSyntaxVersionNumber = value;
			}
		}
		/// <summary>
		/// Get/sets the syntax level.
		/// </summary>
		public char SyntaxLevel
		{
			get
			{
				return mSyntaxLevel;
			}
			set
			{
				mSyntaxLevel = value;
			}
		}
		/// <summary>
		/// Get/sets whether to write out the UNA segment when exporting or not.
		/// </summary>
		public bool WriteUNA
		{
			get
			{
				return mWriteUNA;
			}
			set
			{
				mWriteUNA = value;
			}
		}
		#endregion
	}
}