////////////////////////////////////////////////////////////////////////
//
// EDISCRIPTSettings.cs
//
// This file was generated by MapForce 2021r3.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

namespace Altova.TextParser.EDI
{
	/// <summary>
	/// Encapsulates NCPDP SCRIPT specific settings
	/// </summary>
	public class EDIScriptSettings : EDIFactSettings
	{
		#region Implementation Detail:
		#endregion
		#region Public Interface:
		
		public EDIScriptSettings () 
		{
			mEDIStandard = EDIStandard.EDISCRIPT;
			mControllingAgency = "UNO";
			SyntaxVersionNumber = 0;
		}
		
		#endregion
	}
}