////////////////////////////////////////////////////////////////////////
//
// vmf/vmf1_inputtoresult.cs
//
// This file was generated by MapForce 2021r3.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Xml;
using Altova.Types;
using Altova.Xml;
using Altova.Functions;
using Altova.TextParser;


using bookstore_com_catalog; // application.libraries
namespace vmf
{

	public class vmf1_inputtoresult : Altova.TraceProvider
	{


		class Main : IEnumerable
		{
			private readonly string var1_input;

			public Main(
				string var1_input
			)
			{
				this.var1_input = var1_input;
			}

			public IEnumerator GetEnumerator() { return Altova.Mapforce.MFEmptySequence.Instance.GetEnumerator(); }
		}


		public static IEnumerable Create(
			string var1_input
		)
		{
			object o = hash[var1_input];
			if (o != null)
				return new Altova.Mapforce.MFSingletonSequence(o);
			else
				return new Altova.Mapforce.MFSingletonSequence("Unknown");
		}

		private static readonly Hashtable hash = new Hashtable();
		static vmf1_inputtoresult()
		{
			hash["Science Fiction"] = "A32";
			hash["Romance"] = "C1";
			hash["Computer"] = "A1";
		}

		public static string Eval(
			string var1_input
		)
		{

			IEnumerator e = Create(var1_input).GetEnumerator();
			if (e.MoveNext())
			{
				string result = (string)e.Current;
				Altova.Mapforce.MFEnumerator.Dispose(e);
				return result;
			}
			Altova.Mapforce.MFEnumerator.Dispose(e);
			throw new Exception("Expected a function result.");		
		}

	}
}
