//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingFunctions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MappingFunctions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;category&quot;: &quot;Romance&quot;,
        ///        &quot;shelf&quot;: &quot;A1&quot;
        ///    },
        ///    {
        ///        &quot;category&quot;: &quot;Horror&quot;,
        ///        &quot;shelf&quot;: &quot;A2&quot;
        ///    },
        ///    {
        ///        &quot;category&quot;: &quot;Computer&quot;,
        ///        &quot;shelf&quot;: &quot;A3&quot;
        ///    },
        ///    {
        ///        &quot;category&quot;: &quot;Science Fiction&quot;,
        ///        &quot;shelf&quot;: &quot;A4&quot;
        ///    },
        ///    {
        ///        &quot;category&quot;: &quot;Math&quot;,
        ///        &quot;shelf&quot;: &quot;A5&quot;
        ///    },
        ///    {
        ///        &quot;category&quot;: &quot;Crime&quot;,
        ///        &quot;shelf&quot;: &quot;A6&quot;
        ///    },
        ///    {
        ///        &quot;category&quot;: &quot;Fantasy&quot;,
        ///        &quot;shelf&quot;: &quot;A7&quot;
        ///    }
        ///].
        /// </summary>
        internal static string Shelfs {
            get {
                return ResourceManager.GetString("Shelfs", resourceCulture);
            }
        }
    }
}
