////////////////////////////////////////////////////////////////////////
//
// IDataElement.cs
//
// This file was generated by MapForce 2021r3.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

using System;
using System.Collections;

namespace Altova.TextParser
{
	/// <summary>
	/// Common interface for all generated types.
	/// </summary>
	public interface IDataElement
	{
		/// <summary>
		/// Gets the name of this instance.
		/// </summary>
		string Name {get;}
		/// <summary>
		/// Gets the value of this instance.
		/// </summary>
		string Value {get;}
		/// <summary>
		/// Gets all child elements of this instance.
		/// </summary>
		IEnumerable Children {get;}
	}
}
